Repository FalkorDB/falkordb-dbaas, pull requests merged in 2024-02, with the labels that each got.

#10 Feature/add gcp support
  .github/workflows/gcp-full-infra-test-apply.yaml
  .github/workflows/gcp-full-infra-test-plan.yaml
  .gitignore
  tofu/gcp/tenant/outputs.tf
  tofu/gcp/tenant/resources/k8s/falkordb-backup/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-backup/variables.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/outputs.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/variables.tf
  tofu/gcp/tenant/resources/k8s/main.tf
  tofu/gcp/tenant/variables.tf
  tofu/gcp/tenant_group/.terraform.lock.hcl
  tofu/gcp/tenant_group/resources/cluster/main.tf
  tofu/gcp/tenant_group/resources/k8s/monitoring/main.tf
Labels: size:L

#12 Feature/add network policies
  .github/workflows/gcp-full-infra-test-apply.yaml
  README.md
  tofu/gcp/tenant/resources/k8s/falkordb-backup/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-backup/variables.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/outputs.tf
  tofu/gcp/tenant/resources/k8s/main.tf
  tofu/gcp/tenant/resources/k8s/policies/main.tf
  tofu/gcp/tenant/resources/k8s/policies/variables.tf
  tofu/gcp/tenant/resources/k8s/variables.tf
  tofu/gcp/tenant_group/resources/cluster/main.tf
Labels: size:L, lgtm

#19 Feature/node pool sizing
  .github/workflows/gcp-full-infra-test-plan.yaml
  tofu/gcp/org/.terraform.lock.hcl
  tofu/gcp/org/main.tf
  tofu/gcp/org/providers.tf
  tofu/gcp/org/resources/shared/billing/main.tf
  tofu/gcp/org/resources/shared/billing/variables.tf
  tofu/gcp/org/resources/shared/main.tf
  tofu/gcp/org/resources/shared/variables.tf
  tofu/gcp/org/variables.tf
  tofu/gcp/tenant/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-multi-zone/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-multi-zone/variables.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-single-zone/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-single-zone/variables.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-standalone/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-standalone/variables.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/variables.tf
  tofu/gcp/tenant/resources/k8s/main.tf
  tofu/gcp/tenant/resources/k8s/variables.tf
  tofu/gcp/tenant/variables.tf
  tofu/gcp/tenant_group/main.tf
  tofu/gcp/tenant_group/resources/backup/main.tf
  tofu/gcp/tenant_group/resources/backup/variables.tf
  tofu/gcp/tenant_group/resources/cluster/main.tf
  tofu/gcp/tenant_group/resources/cluster/variables.tf
  tofu/gcp/tenant_group/resources/dns/main.tf
  tofu/gcp/tenant_group/resources/dns/variables.tf
  tofu/gcp/tenant_group/resources/networking/main.tf
  tofu/gcp/tenant_group/variables.tf
  tofu/gcp/test_env/main.tf
  tofu/gcp/test_env/variables.tf
Labels: enhancement, size:XL

#22 Initial PR of Management
  management/.env.local.template
  management/.eslintrc.json
  management/.gitignore
  management/app/api/auth/[...nextauth]/options.ts
  management/app/api/auth/[...nextauth]/route.ts
  management/app/components/GoogleAnalytics.tsx
  management/app/components/SinginProviders.tsx
  management/app/components/navbar.tsx
  management/app/components/spinning.tsx
  management/app/dashboard/layout.tsx
  management/app/dashboard/page.tsx
  management/app/global-error.tsx
  management/app/layout.tsx
  management/app/page.tsx
  management/app/policy/page.tsx
  management/app/providers.tsx
  management/app/terms/page.tsx
  management/components/icons/aws.tsx
  management/components/icons/github.tsx
  management/components/icons/google.tsx
  management/components/ui/label.tsx
  management/components/ui/resizable.tsx
  management/components/ui/skeleton.tsx
  management/components/ui/switch.tsx
  management/components/ui/toast.tsx
  management/components/ui/toaster.tsx
  management/components/ui/use-toast.ts
  management/lib/utils.ts
  management/next.config.js
  management/next.config.mjs
  management/package-lock.json
  management/package.json
  management/sentry.client.config.ts
  management/sentry.edge.config.ts
  management/sentry.server.config.ts
  management/tsconfig.json
Labels: size:XXL

#25 fix #24 add avatar
  management/app/components/AvatarButton.tsx
  management/app/components/navbar.tsx
  management/app/dashboard/layout.tsx
  management/app/dashboard/page.tsx
  management/components/ui/avatar.tsx
  management/components/ui/dropdown-menu.tsx
  management/components/ui/hover-card.tsx
  management/package-lock.json
  management/package.json
Labels: size:L

#31 fix #30 add create database pages
  management/app/api/project/[project]/database/[database]/route.ts
  management/app/api/project/[project]/database/route.ts
  management/app/api/project/[project]/route.ts
  management/app/api/project/route.ts
  management/app/components/navbar.tsx
  management/app/dashboard/databases/new/page.tsx
  management/app/dashboard/databases/sample/page.tsx
  management/app/dashboard/page.tsx
Labels: size:L

#33 fix 32 fit to screen
  management/app/components/navbar.tsx
  management/app/dashboard/databases/new/page.tsx
  management/app/dashboard/databases/sample/page.tsx
Labels: size:M

#21 fix pod anti affinity
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-single-zone/main.tf
Labels: size:S, lgtm

#34 Feature/add deployment tests
  .github/workflows/gcp-full-infra-test-apply.yaml
  requirements.txt
  tofu/gcp/tenant/main.tf
  tofu/gcp/tenant/outputs.tf
  tofu/gcp/tenant/resources/k8s/falkordb-backup/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-multi-zone/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-multi-zone/variables.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-single-zone/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-single-zone/variables.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/labeler/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/labeler/variables.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/variables.tf
  tofu/gcp/tenant/resources/k8s/main.tf
  tofu/gcp/tenant/resources/k8s/outputs.tf
  tofu/gcp/tenant/resources/k8s/policies/main.tf
  tofu/gcp/tenant/resources/k8s/variables.tf
  tofu/gcp/tenant/variables.tf
  tofu/gcp/test_env/__tests__/replica/conftest.py
  tofu/gcp/test_env/__tests__/replica/main.py
  tofu/gcp/test_env/__tests__/standalone/conftest.py
  tofu/gcp/test_env/__tests__/standalone/main.py
  tofu/gcp/test_env/main.tf
  tofu/gcp/test_env/outputs.tf
Labels: enhancement, size:XL, lgtm

#36 Refactor/remove proxy network
  tofu/gcp/tenant/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-multi-zone/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-multi-zone/variables.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-single-zone/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-single-zone/variables.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-standalone/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-standalone/variables.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/variables.tf
  tofu/gcp/tenant/resources/k8s/main.tf
  tofu/gcp/tenant/resources/networking/main.tf
  tofu/gcp/tenant/resources/networking/variables.tf
  tofu/gcp/tenant_group/main.tf
  tofu/gcp/tenant_group/resources/cluster/main.tf
  tofu/gcp/tenant_group/resources/dns/main.tf
  tofu/gcp/tenant_group/resources/dns/outputs.tf
  tofu/gcp/tenant_group/resources/dns/variables.tf
  tofu/gcp/tenant_group/resources/k8s/external_dns/main.tf
  tofu/gcp/tenant_group/resources/k8s/external_dns/variables.tf
  tofu/gcp/tenant_group/resources/k8s/main.tf
  tofu/gcp/tenant_group/resources/k8s/variables.tf
  tofu/gcp/tenant_group/resources/networking/main.tf
Labels: enhancement, size:L

#39 Feature/cluster backup
  README.md
  tofu/gcp/tenant_group/main.tf
  tofu/gcp/tenant_group/outputs.tf
  tofu/gcp/tenant_group/resources/cluster-backup/main.tf
  tofu/gcp/tenant_group/resources/cluster-backup/outputs.tf
  tofu/gcp/tenant_group/resources/cluster-backup/variables.tf
  tofu/gcp/tenant_group/resources/deployment-backup/main.tf
  tofu/gcp/tenant_group/resources/deployment-backup/outputs.tf
  tofu/gcp/tenant_group/resources/deployment-backup/variables.tf
  tofu/gcp/tenant_group/resources/k8s/backup/main.tf
  tofu/gcp/tenant_group/resources/k8s/backup/variables.tf
  tofu/gcp/tenant_group/resources/k8s/main.tf
  tofu/gcp/tenant_group/resources/k8s/variables.tf
  tofu/gcp/tenant_group/variables.tf
Labels: enhancement, size:L, lgtm

#40 add quota alerts
  tofu/gcp/org/main.tf
  tofu/gcp/org/resources/shared/billing/main.tf
  tofu/gcp/org/resources/shared/billing/variables.tf
  tofu/gcp/org/resources/shared/main.tf
  tofu/gcp/org/resources/shared/monitoring/alerts/main.tf
  tofu/gcp/org/resources/shared/monitoring/alerts/variables.tf
  tofu/gcp/org/resources/shared/monitoring/main.tf
  tofu/gcp/org/resources/shared/monitoring/variables.tf
  tofu/gcp/org/resources/shared/variables.tf
  tofu/gcp/org/variables.tf
Labels: size:L

#43 Feature/set maxmemory
  tofu/gcp/org/resources/workloads/application_plane/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-multi-zone/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-single-zone/main.tf
  tofu/gcp/tenant/resources/k8s/falkordb-deployment/falkordb-deployment-standalone/main.tf
  tofu/gcp/tenant_group/resources/cluster/main.tf
Labels: size:M
